__version__ = "0.1.0"

from .client import CodeVFClient
from .exceptions import (
    APIConnectionError,
    APIError,
    AuthenticationError,
    AttachmentLimitExceededError,
    AttachmentTooLargeError,
    BadRequestError,
    CodeVFError,
    IdempotencyConflictError,
    InsufficientCreditsError,
    InvalidMetadataError,
    InvalidModeError,
    InvalidTagError,
    MaxCreditsExceededError,
    NotFoundError,
    PayloadTooLargeError,
    RateLimitError,
    ServerError,
)
from .models import (
    ALL_CATEGORIES,
    Attachment,
    CreditBalance,
    Project,
    ServiceMode,
    TaskCreatePayload,
    TaskDeliverable,
    TaskResponse,
    TaskResult,
    Tag,
    calculate_final_credit_cost,
    normalize_attachments,
)
from .resources import Credits, Projects, Tags, Tasks
from .utils import validate_metadata

__all__ = [
    "__version__",
    "CodeVFClient",
    "CodeVFError",
    "APIConnectionError",
    "APIError",
    "AuthenticationError",
    "AttachmentLimitExceededError",
    "AttachmentTooLargeError",
    "BadRequestError",
    "IdempotencyConflictError",
    "InsufficientCreditsError",
    "InvalidMetadataError",
    "InvalidModeError",
    "InvalidTagError",
    "MaxCreditsExceededError",
    "NotFoundError",
    "PayloadTooLargeError",
    "RateLimitError",
    "ServerError",
    "Project",
    "Tag",
    "CreditBalance",
    "ServiceMode",
    "TaskCreatePayload",
    "TaskDeliverable",
    "TaskResult",
    "TaskResponse",
    "calculate_final_credit_cost",
    "normalize_attachments",
    "Credits",
    "Projects",
    "Tags",
    "Tasks",
    "validate_metadata",
]
